---
- name: Check if Vault-Lookup credential exists
  uri:
    url: "{{ awx_url }}/credentials/?name=Vault-Lookup"
    method: GET
    headers:
      Authorization: "Bearer {{ awx_token }}"
    return_content: yes
  register: vault_cred_check

- name: Set vault_cred_id if it exists
  set_fact:
    vault_cred_id: "{{ vault_cred_check.json.results[0].id }}"
  when: vault_cred_check.json.count > 0

- name: Create Vault Lookup Credential with AppRole if it doesn't exist
  uri:
    url: "{{ awx_url }}/credentials/"
    method: POST
    headers:
      Authorization: "Bearer {{ awx_token }}"
      Content-Type: "application/json"
    body_format: json
    body: |
      {
        "name": "Vault-Lookup",
        "description": "Vault secret lookup with AppRole for network creds",
        "organization": {{ organization_id }},
        "credential_type": 27,
        "inputs": {
          "url": "{{ vault_addr }}",
          "token": "{{ vault_token }}",
          "api_version": "v2",
          "role_id": "{{ vault_approle_role_id }}",
          "secret_id": "{{ vault_approle_secret_id }}"
        }
      }
    status_code: 201
  register: vault_cred_create
  when: vault_cred_check.json.count == 0

- name: Set vault_cred_id from creation
  set_fact:
    vault_cred_id: "{{ vault_cred_create.json.id }}"
  when: vault_cred_check.json.count == 0

- name: Debug vault_cred_id
  debug:
    msg: "Vault Credential ID: {{ vault_cred_id }}"

- name: Create Network Credentials for each device
  uri:
    url: "{{ awx_url }}/credentials/"
    method: POST
    headers:
      Authorization: "Bearer {{ awx_token }}"
      Content-Type: "application/json"
    body_format: json
    body: |
      {
        "name": "{{ item }}",
        "description": "Credentials for {{ item }}",
        "organization": {{ organization_id }},
        "credential_type": 1,
        "inputs": {}
      }
    status_code: 201, 400
  loop: "{{ device_names.split(',') }}"
  register: network_cred_create

- name: Link Vault Lookup Credential for username
  uri:
    url: "{{ awx_url }}/credentials/{{ network_cred_create.results[loop_index].json.id }}/credentials/"
    method: POST
    headers:
      Authorization: "Bearer {{ awx_token }}"
      Content-Type: "application/json"
    body_format: json
    body: |
      {
        "credential": {{ vault_cred_id }},
        "inputs": {
          "secret_path": "{{ vendor }}/{{ item }}",
          "secret_key": "username"
        },
        "kind": "username"
      }
    status_code: 201
  loop: "{{ device_names.split(',') }}"
  loop_control:
    index_var: loop_index
  when: network_cred_create.results[loop_index].status == 201

- name: Link Vault Lookup Credential for password
  uri:
    url: "{{ awx_url }}/credentials/{{ network_cred_create.results[loop_index].json.id }}/credentials/"
    method: POST
    headers:
      Authorization: "Bearer {{ awx_token }}"
      Content-Type: "application/json"
    body_format: json
    body: |
      {
        "credential": {{ vault_cred_id }},
        "inputs": {
          "secret_path": "{{ vendor }}/{{ item }}",
          "secret_key": "password"
        },
        "kind": "password"
      }
    status_code: 201
  loop: "{{ device_names.split(',') }}"
  loop_control:
    index_var: loop_index
  when: network_cred_create.results[loop_index].status == 201