---
# To be used with save_scf.yml
- name: Save an SCF
  f5networks.f5_modules.bigip_command:
    commands: save sys config file {{ inventory_hostname }}_{{ ansible_date_time.date }}
    provider: "{{ provider }}"

- name: Compare SCF files using shell diff
  ansible.builtin.shell: diff -y --suppress-common-lines /var/local/scf/{{ inventory_hostname }}_{{ ansible_date_time.date }} /var/local/scf/{{ inventory_hostname }}
  register: diff_output
  delegate_to: "{{ inventory_hostname }}"

- name: Show diff results
  debug:
    msg: "{{ diff_output.stdout }}"

- name: Delete the SCF file
  f5networks.f5_modules.bigip_command:
  commands: delete sys config file {{ inventory_hostname }}_{{ ansible_date_time.date }}
  provider: "{{ provider }}"