---
# To use with scf_create_baseline.yml
- name: Save an SCF
  f5networks.f5_modules.bigip_command:
    commands: save sys config file {{ inventory_hostname }}_current no-passphrase
    provider: "{{ provider }}"

- name: Compare SCF files using shell diff
  ansible.builtin.shell: diff -y --suppress-common-lines /var/local/scf/{{ inventory_hostname }}_current /var/local/scf/{{ inventory_hostname }}_baseline
  register: diff_output
  delegate_to: "{{ inventory_hostname }}"

- name: Show diff results
  debug:
    msg: "{{ diff_output.stdout }}"
