---
- name: Check all variables
  ansible.builtin.assert:
    that:
      - ansible_host is defined

- name: Create temporary session file
  ansible.builtin.tempfile:
    state: file
    suffix: ".json"
  register: temp_session_file

- name: Login to Check Point API
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/web_api/login"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      api-key: "{{ api_key }}"
    return_content: yes
    validate_certs: no
  register: login_response
  no_log: true

# Write session data to temporary file
- name: Populate temporary session file
  ansible.builtin.copy:
    content: |
      {
        "sid": "{{ login_response.json.sid }}",
        "url": "https://{{ ansible_host }}/web_api",
        "server": "{{ ansible_host }}"
      }
    dest: "{{ temp_session_file.path }}"
  when: login_response.status == 200
