---
- name: Add host object
  check_point.mgmt.cp_mgmt_host:
    name: "{{ host_name }}"
    ip_address: "{{ host_ip }}"
    state: present
    auto_publish_session: true
    session_file: "{{ session_file }}"
  when: task_type == "add_host" and host_ip is defined and host_ip != ""

- name: Delete host object
  check_point.mgmt.cp_mgmt_host:
    name: "{{ host_name }}"
    state: absent
    auto_publish_session: true
    session_file: "{{ session_file }}"
  when: task_type == "delete_host"
