---
- name: Get user attributes from Keycloak group
  ansible.builtin.uri:
    url: "http://keycloak.awx.svc.cluster.local:8080/admin/realms/awx-realm/groups/{{ group_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
    status_code: 200
  register: user_response
  run_once: true

- name: Set credentials as hostvars for targeted hosts
  set_fact:
    credentials: >-
      {{
        credentials | default({}) | combine({
          inventory_hostname: {
            'ansible_user': user_response.json.attributes["host_" + inventory_hostname + "_username"] | default([]) | first,
            'ansible_password': user_response.json.attributes["host_" + inventory_hostname + "_password"] | default([]) | first
          }
        })
      }}
  when: 
    - user_response.json.attributes["host_" + inventory_hostname + "_username"] is defined
    - user_response.json.attributes["host_" + inventory_hostname + "_password"] is defined

- name: Show credentials
  debug:
    var: credentials