---
- name: Login to Ivanti Connect Secure
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/realm_auth"
    method: POST
    force_basic_auth: true
    user: "admin"
    password: "[3kVN-scZpM4oXQSLh2D"
    body: "{ \"realm\": \"Admin Users\" }"
    body_format: json
    return_content: true
    validate_certs: false
  register: auth_response
  ignore_errors: true

- name: Set oauth variable
  ansible.builtin.set_fact:
    oauth: "{{ auth_response.content | from_json }}"
  when: auth_response.content is defined

- name: Set authorization data
  vars:
    authorization_data: "{{ oauth['api_key'] }}:"
  ansible.builtin.set_fact:
    authorization: "{{ authorization_data | b64encode }}"
  when: oauth['api_key'] is defined

- name: Get version
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/system/system-information"
    method: GET
    headers:
      Accept: "application/json"
      Authorization: 'Basic {{ authorization }}'
    body_format: json
    return_content: true
    validate_certs: false
    status_code: [200, 401, 403]
  when: authorization is defined
  register: version_response

- name: Get terminal service profile list 
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/configuration/users/resource-profiles/terminal-services-profiles/terminal-services-profile"
    method: GET
    headers:
      Accept: "application/json"
      Authorization: 'Basic {{ authorization }}'
    body_format: json
    return_content: true
    validate_certs: false
  when: authorization is defined
