---
- name: Try to authenticate to legacy Pulse
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/auth"
    method: GET
    force_basic_auth: true
    user: "admin"
    password: "[3kVN-scZpM4oXQSLh2D"
    # body: "{{ provider }}"
    body_format: json
    return_content: true
    validate_certs: false
  register: auth_response
  ignore_errors: true

- name: Set oauth variable
  when:
    - auth_response.content is defined
  ansible.builtin.set_fact:
    oauth: "{{ auth_response.content | from_json }}"

- name: Set authorization data
  when:
    - oauth['api_key'] is defined
  vars:
    authorization_data: "{{ oauth['api_key'] }}:"
  ansible.builtin.set_fact:
    authorization: "{{ authorization_data | b64encode }}"
