---
- name: Try to authenticate to legacy Pulse
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/auth"
    method: GET
    force_basic_auth: true
    user: "{{ vault_username | ocd.utils.decrypt_vault }}"
    password: "{{ vault_password | ocd.utils.decrypt_vault }}"
    # body: "{{ provider }}"
    body_format: json
    return_content: true
    validate_certs: false
  register: auth_response_legacy
  ignore_errors: true
