---
- name: Fetch credentials from Vault for this host
  ansible.builtin.set_fact:
    vault_creds: "{{ lookup('community.hashi_vault.hashi_vault', vault_secret_path, url='http://10.255.32.212:30200', token='hvs.kF12bGKaScbSqmeSztGMVFur') }}"
  vars:
    vault_secret_path: "{{ (group_names | intersect(awx_hosts_vendor_selection)) | first }}/data/{{ inventory_hostname }}"
  when: inventory_hostname != 'localhost'

- name: Set Ansible connection variables
  ansible.builtin.set_fact:
    ansible_user: "{{ (vault_creds.data.username if vault_creds.data is defined else vault_creds.username) | default('') }}"
    ansible_password: "{{ (vault_creds.data.password if vault_creds.data is defined else vault_creds.password) | default('') }}"
  when: vault_creds is defined

- name: Debug connection details
  ansible.builtin.debug:
    msg: "Connecting to {{ inventory_hostname }} as {{ ansible_user }}"
  when: inventory_hostname != 'localhost'

- name: Get system status from Fortigate
  fortinet.fortios.fortios_monitor_fact:
    selectors: "system.status"
    vdom: "{{ vdom }}"
  register: system_status
  when: inventory_hostname != 'localhost'

- name: Display system status
  ansible.builtin.debug:
    var: system_status
  when: system_status is defined