- name: List ASM policies that are enabled and their enforcement mode
  f5networks.f5_modules.bigip_command:
    commands:
      - list asm policy blocking-mode active inactive
    provider: "{{ provider }}"
  register: asm_pol_status

- name: Normalize stdout
  set_fact:
    normalized_stdout: "{{ asm_pol_status.stdout | join('\n') | regex_replace('\\n\\s+', '\\n') }}"

- name: Check if all active ASM policies have blocking-mode enabled
  set_fact:
    asm_pol_mode: >-
      {{
      '✔' if normalized_stdout.stdout is defined and normalized_stdout.stdout | length > 0 and normalized_stdout.stdout | regex_search('active\\s+blocking-mode\\s+disabled') is none
      else '✖'
      }}

- name: Set ASM enabled check notes
  set_fact:
    asm_pol_notes: >-
      {{
      'All active ASM policies have blocking-mode enabled' if asm_pol_mode == '✔'
      else 'One or more active ASM policies have blocking-mode disabled or no active policies found'
      }}

- name: Append ASM enabled check to results
  set_fact: 
    check_results: "{{ check_results + [{
      'check_category': 'WAF Policy Management',
      'check_item': 'ASM/WAF policies applied and enforced',
      'status': asm_pol_mode,
      'notes': asm_pol_notes
      }] }}"