- name: List ASM provisioning status
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys provision asm
    provider: "{{ provider }}"
  register: asm_provision_result

- name: Set ASM provisioned fact
  set_fact:
    asm_provisioned: "{{ 'true' if asm_provision_result.stdout | regex_search('level\\s+nominal') else 'false' }}"

- name: List ASM policies that are enabled and their enforcement mode
  f5networks.f5_modules.bigip_command:
    commands:
      - list asm policy blocking-mode active inactive
    provider: "{{ provider }}"
  register: asm_pol_status
  when: asm_provisioned | bool

- name: Check if all active ASM policies have blocking-mode enabled
  set_fact:
    asm_pol_mode: >-
      {{
      '✔' if asm_provisioned | bool and asm_pol_status.stdout is defined and asm_pol_status.stdout | length > 0 and not (asm_pol_status.stdout_lines | join('\n') | split('}') | select('match', '.*active.*blocking-mode\\s+disabled.*') | list)
      else '✖'
      }}

- name: Set ASM enabled check notes
  set_fact:
    asm_pol_notes: >-
      {{
      'ASM is provisioned and all active ASM policies have blocking-mode enabled' if asm_pol_mode == '✔'
      else 'ASM is not provisioned or one or more active ASM policies have blocking-mode disabled or no active policies found'
      }}

- name: Append ASM enabled check to results
  set_fact: 
    check_results: "{{ check_results + [{
      'check_category': 'Virtual Servers & App Security',
      'check_item': 'ASM/WAF policies applied and enforced',
      'status': asm_pol_mode,
      'notes': asm_pol_notes
      }] }}"