- name: List client-ssl profile options
  f5networks.f5_modules.bigip_command:
    commands:
      - run util bash -c "tmsh -q -c 'cd /; list ltm profile client-ssl recursive options'"
    provider: "{{ provider }}"
  register: clientssl_options

- name: Parse non-default profiles for no-tlsv1 and no-tlsv1.1
  set_fact:
    clientssl_profile_options: "{{ '✖' if clientssl_options.stdout | regex_search('ltm profile client-ssl (?!(Common/clientssl|Common/clientssl-insecure-compatible|Common/clientssl-quic|Common/clientssl-secure|Common/crypto-server-default-clientssl|Common/splitsession-default-clientssl|Common/wom-default-clientssl))(\\S+/)?\\S+\\s*{((?!no-tlsv1).)*(?!no-tlsv1\\.1).*}') else '✔' }}"

- name: Set clientssl profile options check notes
  set_fact:
    clientssl_profile_options_notes: >-
      {{ 'TLSv1 and 1.1 are disabled' if clientssl_profile_options == '✔' else 'Client-ssl options allow weak TLS protocol versions' }}

- name: Append clientssl tls options check to results
  set_fact:
    hardening_check_results: "{{ hardening_check_results + [{
      'check_category': 'SSL/TLS Security',
      'check_item': 'TLS 1.0 and 1.1 are disabled',
      'status': clientssl_profile_options,
      'notes': clientssl_profile_options_notes
      }] }}"
