- name: List client-ssl profile ciphers
  f5networks.f5_modules.bigip_command:
    commands:
      - run util bash -c "tmsh -q -c 'cd /; list ltm profile client-ssl recursive ciphers'"
    provider: "{{ provider }}"
  register: clientssl_ciphers

- name: Parse non-default profiles for secure cipher suites
  set_fact:
    clientssl_profile_ciphers: "{{ '✖' if (clientssl_ciphers.stdout | join('\n')) | regex_search('ltm profile client-ssl (?!(Common/clientssl|Common/clientssl-insecure-compatible|Common/clientssl-quic|Common/clientssl-secure|Common/crypto-server-default-clientssl|Common/splitsession-default-clientssl|Common/wom-default-clientssl)).*? { ciphers\\s+(?!none)(DEFAULT|ALL|.*?(DES|3DES|RC4|MD5|ADH|EXP).*?)\\s*}') else '✔' }}"

- name: Set clientssl cipher suites check notes
  set_fact:
    clientssl_profile_ciphers_notes: "{{ 'Secure cipher suites are configured' if clientssl_profile_ciphers == '✔' else 'Client-ssl ciphers include insecure suites' }}"

- name: Append clientssl cipher suites check to results
  set_fact:
    check_results: "{{ check_results + [{
      'check_category': 'SSL/TLS Security',
      'check_item': 'Only secure cipher suites are enabled',
      'status': clientssl_profile_ciphers,
      'notes': clientssl_profile_ciphers_notes
      }] }}"