- name: Define vars
  set_fact:
    excel_report: "./f5_report.xlsx"
    hardening_check_results: []
    ssl_check_results: []
    waf_check_results: []

- name: Include mgmt_acl task
  ansible.builtin.import_tasks: mgmt_acl.yml

- name: Include mgmt_services task
  ansible.builtin.import_tasks: mgmt_services.yml

- name: Include ntp_config task
  ansible.builtin.import_tasks: ntp_config.yml

- name: Include dns_config task
  ansible.builtin.import_tasks: dns_config.yml

- name: Include syslog_config task
  ansible.builtin.import_tasks: syslog_config.yml

- name: Include password_policy task
  ansible.builtin.import_tasks: password_policy.yml

- name: Include rbac_settings task
  ansible.builtin.import_tasks: rbac_settings.yml

- name: Include remote_auth task
  ansible.builtin.import_tasks: remote_auth.yml

- name: Include fallback_to_local task
  ansible.builtin.import_tasks: fallback_to_local.yml

- name: Include clientssl_options task
  ansible.builtin.import_tasks: clientssl_options.yml

- name: Include clientssl_ciphers task
  ansible.builtin.import_tasks: clientssl_ciphers.yml

- name: Include cert_key_size task
  ansible.builtin.import_tasks: cert_key_size.yml

- name: Include cert_validator_enabled task
  ansible.builtin.import_tasks: cert_validator_enabled.yml

- name: Include unused_modules task
  ansible.builtin.import_tasks: unused_modules.yml

- name: Include no_deprecated_protocols task
  ansible.builtin.import_tasks: no_deprecated_protocols.yml

- name: Include ssl_key_exchange task
  ansible.builtin.import_tasks: ssl_key_exchange.yml

- name: List ASM provisioning status
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys provision asm
    provider: "{{ provider }}"
  register: asm_provision_result

- name: Set ASM provisioned fact
  set_fact:
    asm_provisioned: "{{ 'true' if asm_provision_result.stdout | regex_search('level') else 'false' }}"
    
- name: Include asm_active_blocking task
  ansible.builtin.import_tasks: asm_active_blocking.yml
  when: asm_provisioned | bool

- name: Include asm_liveupdate task
  ansible.builtin.import_tasks: asm_liveupdate.yml
  when: asm_provisioned | bool

- name: Calculate Hardening summary metrics
  set_fact:
    hardening_total_checks: "{{ hardening_check_results | length }}"
    hardening_passed_checks: "{{ hardening_check_results | selectattr('status', 'equalto', '✔') | length }}"
    hardening_failed_checks: "{{ hardening_check_results | selectattr('status', 'equalto', '✖') | length }}"
    hardening_na_checks: "{{ hardening_check_results | selectattr('status', 'equalto', 'N/A') | length }}"
    hardening_overall_status: "{{ 'Medium Risk' if (hardening_check_results | selectattr('status', 'equalto', '✖') | length) > 0 else 'Low Risk' }}"

- name: Calculate SSL summary metrics
  set_fact:
    ssl_total_checks: "{{ ssl_check_results | length }}"
    ssl_passed_checks: "{{ ssl_check_results | selectattr('status', 'equalto', '✔') | length }}"
    ssl_failed_checks: "{{ ssl_check_results | selectattr('status', 'equalto', '✖') | length }}"
    ssl_na_checks: "{{ ssl_check_results | selectattr('status', 'equalto', 'N/A') | length }}"
    ssl_overall_status: "{{ 'Medium Risk' if (ssl_check_results | selectattr('status', 'equalto', '✖') | length) > 0 else 'Low Risk' }}"

- name: Calculate WAF summary metrics
  set_fact:
    waf_total_checks: "{{ waf_check_results | length }}"
    waf_passed_checks: "{{ waf_check_results | selectattr('status', 'equalto', '✔') | length }}"
    waf_failed_checks: "{{ waf_check_results | selectattr('status', 'equalto', '✖') | length }}"
    waf_na_checks: "{{ waf_check_results | selectattr('status', 'equalto', 'N/A') | length }}"
    waf_overall_status: "{{ 'Medium Risk' if (waf_check_results | selectattr('status', 'equalto', '✖') | length) > 0 else 'Low Risk' }}"
  when: asm_provisioned | bool

- name: Ensure openpyxl is installed
  ansible.builtin.pip:
    name: openpyxl
    executable: pip3
  run_once: true

- name: Create Excel report directory
  ansible.builtin.file:
    path: "{{ excel_report | dirname }}"
    state: directory
    mode: '0755'

- name: Generate Excel report
  ansible.builtin.template:
    src: f5_report_template.py.j2
    dest: ./f5_report_script.py
    mode: '0755'

- name: Run Excel report generation script
  ansible.builtin.command: python3 ./f5_report_script.py
  changed_when: true

# For testing
- name: Copy Excel to remote host
  ansible.builtin.command:
    cmd: "scp -i /tmp/id_rsa -o StrictHostKeyChecking=no {{ excel_report }} benk@10.255.32.210:/var/tmp/"
