# Custom vars - excel_report: "./f5_report.xlsx", check_results: []
- name: Include mgmt_acl task
  ansible.builtin.include_tasks: mgmt_acl.yml

- name: Include mgmt_services task
  ansible.builtin.include_tasks: mgmt_services.yml

- name: Include ntp_config task
  ansible.builtin.include_tasks: ntp_config.yml

- name: Include dns_config task
  ansible.builtin.include_tasks: dns_config.yml

- name: Include syslog_config task
  ansible.builtin.include_tasks: syslog_config.yml

- name: Include password_policy task
  ansible.builtin.include_tasks: password_policy.yml

- name: Include rbac_settings task
  ansible.builtin.include_tasks: rbac_settings.yml

- name: Include remote_auth task
  ansible.builtin.include_tasks: remote_auth.yml

- name: Calculate summary metrics
  set_fact:
    total_checks: "{{ check_results | length }}"
    passed_checks: "{{ check_results | selectattr('status', 'equalto', '✔') | length }}"
    failed_checks: "{{ check_results | selectattr('status', 'equalto', '✖') | length }}"
    na_checks: "{{ check_results | selectattr('status', 'equalto', 'N/A') | length }}"
    overall_status: "{{ 'Medium Risk' if (check_results | selectattr('status', 'equalto', '✖') | length) > 0 else 'Low Risk' }}"

- name: Ensure openpyxl is installed
  ansible.builtin.pip:
    name: openpyxl
    executable: pip3
  run_once: true

- name: Create Excel report directory
  ansible.builtin.file:
    path: "{{ excel_report | dirname }}"
    state: directory
    mode: '0755'

- name: Generate Excel report
  ansible.builtin.template:
    src: f5_report_template.py.j2
    dest: ./f5_report_script.py
    mode: '0755'

- name: Run Excel report generation script
  ansible.builtin.command: python3 ./f5_report_script.py
  changed_when: true

# For testing
- name: Copy Excel to remote host
  ansible.builtin.command:
    cmd: "scp -i /tmp/id_rsa -o StrictHostKeyChecking=no {{ excel_report }} benk@10.255.32.210:/var/tmp/"
