- name: List DNS configuration
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys dns all-properties
    provider: "{{ provider }}"
  register: dns_config

- name: Check DNS servers
  set_fact:
    dns_servers_status: "{{ '✖' if (dns_config.stdout | regex_search('name-servers none')) else ('✔' if (dns_servers_count | int >= 2 and (dns_config.stdout | regex_search('name-servers {.*(10\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|192\\.168\\.).*'))) else '✖') }}"
  vars:
    dns_servers_count: "{{ 0 if (dns_config.stdout | regex_search('name-servers none')) else (dns_config.stdout | regex_findall('\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b') | length) }}"

- name: Set DNS check notes
  set_fact:
    dns_notes: >-
      {{ 'Internal DNS servers configured' if dns_servers_status == '✔' else 'External or unknown DNS servers configured' }}

- name: Append DNS configuration check to results
  set_fact:
    check_results: "{{ check_results + [{
      'check_category': 'DNS',
      'check_item': 'DNS uses internal servers',
      'status': dns_servers_status,
      'notes': dns_notes
      }] }}"
