---
- name: Register Partitions
  shell: tmsh list auth partition | awk '/auth partition/ {print $3}'
  register: partitions
  delegate_to: "{{ inventory_hostname }}"

- name: Gather subsets
  f5networks.f5_modules.bigip_device_info:
    partition: "{{ item }}"
    gather_subset:
      - virtual-servers
      - ltm-pools
      - license
      - ssl-certs
    provider: "{{ provider }}"
  loop: "{{ partitions.stdout_lines }}"
  register: device_info

- name: Parse data
  set_fact:
    collect_stats:
      virtual_servers: >-
        {{ device_info.results | map(attribute='virtual_servers')
          | flatten
          | items2dict(key_name='full_path', value_name='availability_status') }}
      ltm_pools: >-
        {{ device_info.results | map(attribute='ltm_pools')
          | flatten
          | items2dict(key_name='full_path', value_name='availability_status') }}
      license_info: >-
        {{ device_info.results[0].license | json_query('[0].{max_version: max_permitted_version, expiry: license_end_date}') }}
      ssl_certs: >-
        {{ device_info.results | map(attribute='ssl_certs')
          | flatten
          | items2dict(key_name='full_path', value_name='expiration_date') }}

- name: Generate BIG-IP status report
  template:
    src: health_check_report.j2
    dest: "/tmp/bigip_status_report_{{ inventory_hostname }}.txt"

# Or import upload_to_s3.yml.
- name: Read rendered report content
  slurp:
    src: "/tmp/bigip_status_report_{{ inventory_hostname }}.txt"
  register: report_content

- name: Set job artifact variable
  set_stats:
    data:
      bigip_status_report: "{{ report_content.content | b64decode }}"