- name: Gather management access rules
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys httpd allow
      - list sys sshd allow
      - list security firewall management-ip-rules
    provider: "{{ provider }}"
  register: mgmt_acl

- name: Parse management access rules and set status
  set_fact:
    mgmt_access_status: "{{ '✔' if (not (mgmt_acl.stdout | regex_search('allow\\s*{ All }')) or
                                    not (mgmt_acl.stdout | regex_search('management-ip-rules\\s*{ }')))
                                    else '✖' }}"

- name: Set management access notes
  set_fact:
    mgmt_access_notes: "{{ 'Management access restricted' if mgmt_access_status == '✔' else 'Default configuration detected: HTTPD allows all or no management IP rules' }}"

- name: Append management access check to results
  set_fact:
    check_results: "{{ hardening_check_results + [{
      'check_category': 'Management Access',
      'check_item': 'Management interface access is restricted via ACLs',
      'status': mgmt_access_status,
      'notes': mgmt_access_notes
      }] }}"