- name: List NTP configuration
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys ntp all-properties
    provider: "{{ provider }}"
  register: ntp_config

- name: Check NTP servers
  set_fact:
    ntp_servers_status: "{{ '✖' if (ntp_config.stdout | regex_search('servers none')) else ('✔' if (ntp_servers_count | int >= 2 and (ntp_config.stdout | regex_search('servers {.*(10\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|192\\.168\\.).*'))) else '✖') }}"
  vars:
    ntp_servers_count: "{{ 0 if (ntp_config.stdout | regex_search('servers none')) else (ntp_config.stdout | regex_findall('\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b') | length) }}"

- name: Check if NTP authentication is enabled
  set_fact:
    ntp_auth_enabled: "{{ '✔' if (ntp_config.stdout is search('include.*key')) else '✖' }}"

- name: Set NTP check notes
  set_fact:
    ntp_notes: >-
      {{ 'Internal NTP servers configured' if ntp_servers_status == '✔' else 'External or unknown NTP servers configured' }}
      {{ 'and NTP authentication enabled' if ntp_auth_enabled == '✔' else 'and NTP authentication not enabled' }}

- name: Append NTP configuration check to results
  set_fact:
    hardening_check_results: "{{ hardening_check_results + [{
      'check_category': 'Time Synchronization',
      'check_item': 'NTP uses internal trusted servers with optional authentication',
      'status': ntp_servers_status,
      'notes': ntp_notes
      }] }}"
