- name: List password-policy
  f5networks.f5_modules.bigip_command:
    commands:
      - list auth password-policy
    provider: "{{ provider }}"
  register: password_policy

# Add more requirements.
- name: Check password policy is enabled
  set_fact:
    password_policy_status: "{{ '✖' if password_policy.stdout | regex_search('policy-enforcement disabled') else '✔' }}"

- name: Set password policy check notes
  set_fact:
    password_policy_notes: >-
      {{ 'Password policy enabled' if password_policy_status == '✔' else 'Password policy disabled' }}

- name: Append password policy check to results
  set_fact:
    check_results: "{{ check_results + [{
      'check_category': 'User Accounts & Authentication',
      'check_item': 'Strong password policy enforced',
      'status': password_policy_status,
      'notes': password_policy_notes
      }] }}"
