# Testing
- name: List Users
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - users
    provider: "{{ provider }}"
  register: users

- name: List password-policy
  f5networks.f5_modules.bigip_command:
    commands:
      - list auth password-policy
    provider: "{{ provider }}"
  register: password_policy

# Add more requirements.
- name: Check password policy is enabled
  set_fact:
    password_policy_status: "{{ '✖' if password_policy.stdout | regex_search('policy-enforcement disabled') else '✔' }}"

- name: Set password policy check notes
  set_fact:
    password_policy_notes: >-
      {{ 'Internal DNS servers configured' if dns_servers_status == '✔' else 'External or unknown DNS servers configured' }}

- name: Append DNS configuration check to results
  set_fact:
    check_results: "{{ check_results + [{
      'check_category': 'User Accounts & Authentication',
      'check_item': 'Strong password policy enforced',
      'status': password_policy_status,
      'notes': password_policy_notes
      }] }}"
