---
- name: Download diagnostics pdf
  ansible.builtin.shell: |
    curl --url https://ihealth2-api.f5.com/qkview-analyzer/api/qkviews/"{{ workflow_artifacts.qkview_id[0] }}"/diagnostics.pdf -H "Authorization: Bearer "{{ workflow_artifacts.bearer_token.access_token }}"" -H "Accept: application/vnd.f5.ihealth.api" --user-agent "AnsibleClient" --output "{{ tmp_path + inventory_hostname + '-diagnostics.pdf' }}"
  delegate_to: "{{ inventory_hostname }}"