# Uses SSH key auth defined in AWX Credentials
- name: Copy file to remote SSH server
  hosts: utility01
  tasks:
    - name: Copy Excel to remote host
      ansible.builtin.copy:
        src: "{{ excel_report }}"
        dest: "/var/tmp/"
        mode: '0644'
      delegate_to: localhost