- name: List ssl profile ciphers
  f5networks.f5_modules.bigip_command:
    commands:
      - run util bash -c "tmsh -q -c 'cd /; list ltm profile client-ssl recursive ciphers'"
      - run util bash -c "tmsh -q -c 'cd /; list ltm profile server-ssl recursive ciphers'"
    provider: "{{ provider }}"
  register: ssl_ciphers

- name: Set default profiles
  set_fact:
    default_profiles:
      - Common/clientssl
      - Common/clientssl-insecure-compatible
      - Common/clientssl-quic
      - Common/clientssl-secure
      - Common/crypto-server-default-clientssl
      - Common/splitsession-default-clientssl
      - Common/wom-default-clientssl
      - Common/apm-default-serverssl
      - Common/cloud-service-default-ssl
      - Common/crypto-client-default-serverssl
      - Common/do-not-remove-without-replacement
      - Common/f5aas-default-ssl
      - Common/pcoip-default-serverssl
      - Common/serverssl
      - Common/serverssl-insecure-compatible
      - Common/serverssl-secure
      - Common/shape-api-ssl
      - Common/splitsession-default-serverssl
      - Common/wom-default-serverssl

- name: Normalize stdout
  set_fact:
    normalized_stdout: "{{ ssl_ciphers.stdout | join('\n') | regex_replace('\\n\\s+', '\\n') }}"

- name: Parse client-ssl profiles
  set_fact:
    profiles: "{{ normalized_stdout | regex_findall('ltm profile (client-ssl|server-ssl) ([^\\s]+).*?\\s+{\\s+ciphers\\s+([^}]*)\\s*}', re.MULTILINE) }}"

- name: Check custom profiles for ECDHE/DHE compliance
  set_fact:
    non_compliant_profiles: "{{ profiles | selectattr('0', 'notin', default_profiles) | selectattr('1', 'not_regex', '^(ECDHE|DHE).*') | list }}"
    
- name: Set compliance status
  set_fact:
    ssl_profile_ciphers: "{{ '✔' if non_compliant_profiles | length == 0 else '✖' }}"
    ssl_profile_ciphers_notes: "{{ 'All custom profiles use ECDHE/DHE ciphers' if non_compliant_profiles | length == 0 else 'Non-compliant profiles: ' + (non_compliant_profiles | map(attribute='0') | join(', ')) }}"

- name: Append key exchange check to results
  set_fact:
    ssl_check_results: "{{ ssl_check_results + [{
      'check_category': 'SSL Profiles',
      'check_item': 'Only ECDHE/DHE key exchange enabled in custom profiles',
      'status': ssl_profile_ciphers,
      'notes': ssl_profile_ciphers_notes
      }] }}"