- name: List Syslog configuration
  f5networks.f5_modules.bigip_command:
    commands:
      - list sys syslog all-properties
    provider: "{{ provider }}"
  register: syslog_config

- name: Check Syslog servers
  set_fact:
    syslog_servers_status: "{{ '✖' if (syslog_config.stdout[0] is search('remote-servers none')) else ('✔' if (syslog_config.stdout[0] is search('remote-servers { (10|172|192)\\.'))) else '✖') }}"

- name: Set Syslog check notes
  set_fact:
    syslog_notes: >-
      {{ 'Internal Syslog servers configured' if syslog_servers_status == '✔' else 'External or unknown Syslog servers configured' }}

- name: Append DNS configuration check to results
  set_fact:
    check_results: "{{ check_results + [{
      'check_category': 'Logging & Auditing',
      'check_item': 'Syslog uses internal servers',
      'status': syslog_servers_status,
      'notes': syslog_notes
      }] }}"
