---
- name: Pulse Main Playbook
  hosts: >
    {% if awx_single_hosts_run is defined and awx_single_hosts_run | length > 0 %}
      {{ awx_single_hosts_run }}
    {% elif awx_hosts_vendor_selection is defined %}
      {% if 'pulse' in awx_hosts_vendor_selection %}
        {{ hosts | default('') + 'pulse,' }}
      {% endif %}
      {% if ('pulse' not in awx_hosts_vendor_selection) %}
        none
      {% endif %}
    {% else %}
      localhost
    {% endif %}
  gather_facts: false

  roles:
    - role: pre_tasks
      tags:
        - always
    - role: config
      tags:
        - config

  vars:
    device_https_port: 443
    ansible_connection: local
    validate_certs: false