---
- name: Add host object
  check_point.mgmt.cp_mgmt_host:
    name: "{{ parameters.host_name }}"
    ip_address: "{{ parameters.host_ip }}"
    color: "{{ parameters.color }}"
    state: present
    auto_publish_session: true
    session_file: "{{ session_file }}"
  when: parameters.task_type == "add_host" and parameters.host_ip is defined and parameters.host_ip != ""

- name: Delete host object
  check_point.mgmt.cp_mgmt_host:
    name: "{{ parameters.host_name }}"
    state: absent
    auto_publish_session: true
    session_file: "{{ session_file }}"
  when: parameters.task_type == "delete_host" and parameters.host_name is defined
