---
    - name: Run ping to 8.8.8.8
      ansible.builtin.shell: ping -c 4 8.8.8.8
      register: ping_result
      ignore_errors: yes

    - name: Check for "Reply from 8.8.8.8" in ping output
      ansible.builtin.debug:
        msg: "Ping to 8.8.8.8 was successful"
      when: "'Reply from 8.8.8.8' in ping_result.stdout"
      
    - name: Mark as failure if no reply
      ansible.builtin.fail:
        msg: "Ping to 8.8.8.8 failed"
      when: "'Reply from 8.8.8.8' not in ping_result.stdout"
