---
- name: Execute traceroute
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_port: 22
  ansible.builtin.raw: execute traceroute 1.1.1.1
  register: traceroute_output

- name: Check if specific IP is in traceroute path
  ansible.builtin.set_fact:
    ip_found: "{{ '2.2.2.2' in traceroute_output.stdout }}"

- name: Fail if IP not found
  ansible.builtin.fail:
    msg: "Specific IP 2.2.2.2 not found in traceroute path"
  when: not ip_found
