- name: Gather VS info
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - virtual-servers
    provider: "{{ provider }}"
  register: vs_info

- name: Delete existing Virtual Server (if needed)
  f5networks.f5_modules.bigip_virtual_server:
    name: apm_vs
    partition: Applications
    state: absent
    provider: "{{ provider }}"
  when: vs_info.ansible_facts.ansible_net_virtual_servers | selectattr('name', 'equalto', 'apm_vs') | list | length > 0

- name: Recreate Virtual Server with clean profile list
  f5networks.f5_modules.bigip_virtual_server:
    name: apm_vs
    partition: Applications
    destination: "10.255.38.201:443"
    ip_protocol: tcp
    snat: "automap"
    profiles:
      - name: "/Common/http"
      - name: "/Common/serverssl"
        context: server-side
      - name: "/Common/tcp"
      - name: "/Applications/applications-cp"
        context: client-side
      - name: "/Applications/combined-ap"
      - name: "/Applications/modern-rewrite"
      - name: "/Common/example.com-clientssl"
        context: client-side
    provider: "{{ provider }}"
