- name: Gather Virtual Server info
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - virtual-servers
    partition: "Applications"
    provider: "{{ provider }}"
  register: __virtual_servers

- name: Get profile list from Virtual Server
  ansible.builtin.set_fact:
    __vs_profiles: "{{ (__virtual_servers.ansible_facts.ansible_net_virtual_servers | selectattr('name', 'equalto', f5_vs) | map(attribute='profiles') | first) | map(attribute='full_path') | list }}"
  when: __virtual_servers.ansible_facts.ansible_net_virtual_servers | selectattr('name', 'equalto', f5_vs) | list | length > 0

- name: Debug raw profiles
  ansible.builtin.debug:
    var: __vs_profiles

- name: Initialize converted profiles list
  ansible.builtin.set_fact:
    __vs_converted: "{{ __vs_profiles | reject('equalto', __virtual_servers_profile.name) | list }}"

- name: Add new clientssl profile with context
  ansible.builtin.set_fact:
    __vs_converted: "{{ __vs_converted + [__virtual_servers_profile] }}"
  when: __virtual_servers_profile.name not in __vs_profiles

- name: Debug converted profiles
  ansible.builtin.debug:
    var: __vs_converted

- name: Update Virtual Server with new profile list
  f5networks.f5_modules.bigip_virtual_server:
    name: "{{ f5_vs }}"
    partition: "Applications"
    profiles: "{{ __vs_converted }}"
    provider: "{{ provider }}"
    state: present