# Create a terminal service resource profile and assign to a User Role.
# Retrieve file contents, e.g.
# PC0001
# Ben
# PC0002
# Alice
#
# Iterate over the list, creating a resource profile and/or User Role for every 2 items, respectively.
# Custom variables: pc_user_list (list), domain (static), input_file (txt file)
# To-do: create User Role if it doesn't exist.
---
- name: Read the input file
  ansible.builtin.slurp:
    src: "{{ input_file }}"
  register: file_content
  delegate_to: localhost

- name: Validate file content
  ansible.builtin.fail:
    msg: "Input file must have an even number of lines (pc_name followed by username)."
  when: (file_content.content | b64decode | split('\n') | reject('==', '') | length) % 2 != 0

- name: Create pc_user_list from file content
  ansible.builtin.set_fact:
    pc_user_list: >
      {{ file_content.content | b64decode | split('\n') | reject('==', '') | batch(2) | list }}

- name: Check for duplicate pc_names
  ansible.builtin.fail:
    msg: "Duplicate pc_name found: {{ item[0] }}. Each pc_name must be unique."
  when: (pc_user_list | map('first') | list | unique | length) != (pc_user_list | length)
  loop: "{{ pc_user_list }}"
  loop_control:
    label: "{{ item[0] }}"

- name: Iterate over pc_user_list to create resource profiles
  block:
    - name: Check if the resource profile exists for {{ item[0] }}
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/configuration/users/resource-profiles/terminal-services-profiles/terminal-services-profile/{{ item[0] }}"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: 'Basic {{ authorization }}'
        body_format: json
        force_basic_auth: yes
        validate_certs: false
        status_code: [200, 404]
      register: profiles_response
      loop: "{{ pc_user_list }}"
      loop_control:
        label: "{{ item[0] }} - {{ item[1] }}"

    - name: Set fact for profile existence
      ansible.builtin.set_fact:
        profile_exists: "{{ profiles_response.status == 200 }}"
      when: profiles_response.status is defined
      loop: "{{ pc_user_list }}"
      loop_control:
        label: "{{ item[0] }} - {{ item[1] }}"

    - name: Create Terminal Service Profile and Assign User Role for {{ item[0] }} and {{ item[1] }}
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/configuration/users/resource-profiles/terminal-services-profiles/terminal-services-profile"
        method: POST
        force_basic_auth: yes
        headers:
          Accept: "application/json"
          Authorization: 'Basic {{ authorization }}'
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ item[0] }}"
          roles:
            - "{{ item[1] }} RDP Users"
          wts:
            applet: "Premier Java RDP Applet"
            host: "{{ item[0] }}.{{ domain }}"
            sessions:
              session:
                - alias-name: ""
                  allow-clipboard: "false"
                  application-path: ""
                  apply: "all"
                  auto-launch: "false"
                  color-depth: "32bit"
                  connect-comports: "false"
                  connect-drives: "false"
                  connect-printers: "true"
                  connect-smartcards: "false"
                  description: ""
                  disable-nla: "false"
                  experience-options:
                    bitmap-caching: "false"
                    desktop-background: "false"
                    desktop-composition: "false"
                    font-smoothing: "false"
                    menu-window-animation: "false"
                    show-content-dragging: "false"
                    themes: "false"
                  host: "{{ item[0] }}.{{ domain }}"
                  launch-seamless: "false"
                  microphone-option: "false"
                  multi-mon: "true"
                  name: "{{ item[0] }}"
                  password-type: "variable"
                  path-dir: ""
                  port: "3389"
                  roles: null
                  screen-size: "fullscreen"
                  smartcard-nla: "disabled"
                  sound-options: "bring-to-local"
                  username: "CORPORATE\\{{ item[1] }}"
                  variable-password: ""
        status_code: 201
        validate_certs: false
      register: create_response
      when: profiles_response.status == 404
      loop: "{{ pc_user_list }}"
      loop_control:
        label: "{{ item[0] }} - {{ item[1] }}"

    - name: Retrieve the profile details for {{ item[0] }} and {{ item[1] }}
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ device_https_port }}/api/v1/configuration/users/resource-profiles/terminal-services-profiles/terminal-services-profile/{{ item[0] }}"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: 'Basic {{ authorization }}'
        body_format: json
        force_basic_auth: yes
        validate_certs: false
      when: profiles_response.status == 404
      loop: "{{ pc_user_list }}"
      loop_control:
        label: "{{ item[0] }} - {{ item[1] }}"
  rescue:
    - name: Handle API errors for {{ item[0] }} and {{ item[1] }}
      ansible.builtin.debug:
        msg: "Failed to manage resource profile for {{ item[0] }} and {{ item[1] }}."
      when: create_response.status != 201
      loop: "{{ pc_user_list }}"
      loop_control:
        label: "{{ item[0] }} - {{ item[1] }}"