- name: Assert all variables exist
  ansible.builtin.assert:
    that:
      - task_selection is defined

- name: Include selected task files in order
  ansible.builtin.include_tasks: "roles/config/tasks/{{ task_file }}.yml"
  loop: "{{ task_selection }}"
  loop_control:
    loop_var: task_file
