---
- name: Pre gather facts Playbook
  hosts: localhost
  gather_facts: false

  roles:
    - role: pre_datetime
      tags:
        - pre_check
    - role: pre_awx_info
      tags:
        - pre_check
    - role: keycloak
      tags:
        - jit_creds
    - role: general
      tags:
        - general

  vars:
    ansible_connection: local
    awx_url: "http://awx-service.awx.svc.cluster.local/api/v2"
    awx_token: "AQZjwTwWhzqewaKa7hNUu51RSaItf0"
    vault_addr: "http://10.255.32.212:30200"
    vault_token: "hvs.ZFnGnd3eKmSLRHvBeRx85qkE"
    organization_id: 2