---
- name: Pre gather facts Playbook
  hosts: localhost
  gather_facts: false

  roles:
    - role: pre_datetime
      tags:
        - pre_check
    - role: pre_awx_info
      tags:
        - pre_check
    - role: keycloak
      tags:
        - jit_creds
  
  vars:
    ansible_connection: local
    client_id: "{{ client_id }}"
    client_secret: "{{ client_secret }}"
    keycloak_groups:
      - fg-group