---
- name: AWX Main Playbook
  hosts: localhost
  gather_facts: false

  roles:
    - role: pre_datetime
      tags:
        - pre_check
    - role: pre_awx_info
      tags:
        - pre_check
    - role: general
      tags:
        - general

  vars:
    ansible_connection: local
    awx_url: "http://awx-service.awx.svc.cluster.local"
    awx_token: "AQZjwTwWhzqewaKa7hNUu51RSaItf0"
    vault_addr: "http://10.255.32.212:30200"
    vault_token: "hvs.kF12bGKaScbSqmeSztGMVFur"
    vault_approle_role_id: "8ae43b24-c4e6-a690-548a-b10cc6542250"
    vault_approle_secret_id: "2af43c9b-8f28-60a1-49d9-9a8cc3b76021"
    organization_id: 2

    # Nuclei scan variables
    workspace_dir: "/runner/project"
    template_dir: "{{ workspace_dir }}/nuclei-templates"
    target_file: "{{ workspace_dir }}/targets.txt"
    result_file: "{{ workspace_dir }}/results/scan_{{ lookup('pipe', 'date +%F_%H-%M-%S') }}.txt"
