---
- name: F5 BIG-IP Main Playbook
  hosts: >
    {% if awx_single_hosts_run is defined and awx_single_hosts_run | length > 0 %}
      {{ awx_single_hosts_run }}
    {% elif awx_hosts_vendor_selection is defined %}
      {% if 'bigip' in awx_hosts_vendor_selection %}
        {{ hosts | default('') + 'bigip,' }}
      {% endif %}
      {% if ('bigip' not in awx_hosts_vendor_selection) %}
        none
      {% endif %}
    {% else %}
      localhost
    {% endif %}
  gather_facts: false

  roles:
    - role: pre_tasks
      tags:
        - always
    - role: config
      tags:
        - config
    - role: qkview
      tags:
        - qkview
    - role: customer_issues
      tags:
        - customer
  
  vars:
    ansible_port: 443
    ansible_connection: local
    validate_certs: false
