---
- name: Generate qkview
  block:
    - name: Generate qkview
      f5networks.f5_modules.bigip_qkview:
        exclude_core: true
        filename: "/var/tmp/{{ inventory_hostname }}.qkview"
        only_create_file: true
        provider: "{{ provider }}"
      register: qkview_result
  
  rescue:
    - name: Check if qkview file exists on remote host
      ansible.builtin.wait_for:
        path: "/var/tmp/{{ inventory_hostname }}.qkview"
        state: present
        timeout: 300
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: true
      register: file_check

    - name: Fail if qkview file does not exist
      ansible.builtin.fail:
        msg: "qkview file does not exist after timeout"
      when: file_check.failed

    - name: Notify successful file check
      ansible.builtin.debug:
        msg: "qkview file exists, playbook will continue successfully"
      when: not file_check.failed