---
- name: Generate qkview
  block:
    - name: Generate qkview
      f5networks.f5_modules.bigip_qkview:
        exclude_core: true
        filename: "/var/tmp/{{ inventory_hostname }}.qkview"
        only_create_file: true
        provider: "{{ provider }}"
      register: qkview_result
  
  rescue:
    - name: Check if qkview file exists
      f5networks.f5_modules.bigip_command:
        commands: 'run /util bash -c "test -f /var/tmp/{{ inventory_hostname }}.qkview"'
        provider: "{{ provider }}"
      register: file_check

    - name: Fail if file does not exist
      fail:
        msg: "qkview file does not exist"
      when: file_check.rc != 0