---
- name: Check all variables
  ansible.builtin.assert:
    that:
      - ansible_host is defined

- name: Fetch credentials from Vault for this host
  ansible.builtin.set_fact:
    vault_creds: "{{ lookup('community.hashi_vault.hashi_vault', vault_secret_path, url='http://10.255.32.212:30200', token='hvs.kF12bGKaScbSqmeSztGMVFur') }}"
  vars:
    vault_secret_path: "{{ (group_names | intersect(awx_hosts_vendor_selection)) | first }}/data/{{ inventory_hostname }}"
  when: inventory_hostname != 'localhost'

- name: Set Ansible connection variables
  ansible.builtin.set_fact:
    ansible_user: "{{ (vault_creds.data.username if vault_creds.data is defined else vault_creds.username) | default('') }}"
    ansible_password: "{{ (vault_creds.data.password if vault_creds.data is defined else vault_creds.password) | default('') }}"
  when: vault_creds is defined

- name: Set provider
  ansible.builtin.set_fact:
    provider:
      password: "{{ ansible_password }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: false
      no_f5_teem: true

- name: Gather Device Facts
  f5networks.f5_modules.bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - system-info
      - software-hotfixes
  register: device_facts