---
- name: Check all variables
  ansible.builtin.assert:
    that:
      - ansible_host is defined

- name: Fetch credentials from Vault for this host
  ansible.builtin.set_fact:
    vault_creds: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/bigip', url='http://10.255.32.212:30200', auth_method='approle', role_id='8ae43b24-c4e6-a690-548a-b10cc6542250', secret_id='2af43c9b-8f28-60a1-49d9-9a8cc3b76021') }}"
  vars:
    vault_secret_path: "{{ (group_names | intersect(awx_hosts_vendor_selection)) | first }}/{{ inventory_hostname }}"
  when: inventory_hostname != 'localhost'

- name: Set Ansible connection variables
  ansible.builtin.set_fact:
    ansible_user: "{{ (vault_creds.data.username if vault_creds.data is defined else vault_creds.username) | default('') }}"
    ansible_password: "{{ (vault_creds.data.password if vault_creds.data is defined else vault_creds.password) | default('') }}"
  when: vault_creds is defined

- name: Debug connection details
  ansible.builtin.debug:
    msg: "Connecting to {{ inventory_hostname }} as {{ ansible_user }}"
  when: inventory_hostname != 'localhost'

- name: Set provider
  ansible.builtin.set_fact:
    provider:
      password: "{{ ansible_password }}"
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      validate_certs: false
      no_f5_teem: true

- name: Gather Device Facts
  f5networks.f5_modules.bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - system-info
      - software-hotfixes
  register: device_facts