---
- name: Check all variables
  ansible.builtin.assert:
    that:
      - ansible_host is defined

- name: Gather device facts
  block:
    - name: Set provider
      ansible.builtin.set_fact:
        provider:
          password: "{{ ansible_ssh_pass }}"
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          validate_certs: false
          no_f5_teem: true

    - name: Gather Device Facts
      f5networks.f5_modules.bigip_device_info:
        provider: "{{ provider }}"
        gather_subset:
          - system-info
          - software-hotfixes
      register: device_facts