---
- name: Check all variables
  ansible.builtin.assert:
    that:
      - ansible_host is defined

- name: Gather device facts
  block:
    - name: Login to Check Point Gaia API
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:443/web_api/"
        method: POST
        body_format: json
        body:
          api-key: "{{ api_key }}"
        validate_certs: false
        status_code: 200
      register: login_response

    - name: Set session ID
      ansible.builtin.set_fact:
        session_id: "{{ login_response.json.sid }}"
    
    - name: Get Checkpoint Gaia facts
      check_point.gaia.cp_gaia_version_facts:
      vars:
        ansible_httpapi_extra_args:
          headers:
            X-chkp-sid: "{{ session_id }}"
      register: device_facts
      ignore_errors: true